openapi: '3.0.2'
info:
  title: Quotation API
  description: Quotation API for Quotes
  version: '1.0'
  contact:
    email: dok.x@sdc.dk
servers:
  - url: https://api.server.test/v1
tags:
  - name: RFQ
paths:
  /rfqs:
    post:
      tags:
        - RFQ
      description: Create a quote
      operationid: createQuote
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quotation"
      responses:
        '200':
          description: OK
components:
  schemas:
    Quotation:
      type: object
      properties:
        id:
          type: integer
        product:
          type: string
        quantity:
          type: integer
        price:
          type: number
        shipment:
          type: string
        mode:
          type: string
