openapi: "3.0.2"
info:
    title: Quotation API
    description: Quotation API for Quotes
    version: "1.0"
    contact:
        email: dok.x@sdc.dk
servers:
    - url: https://api.server.test/v1
tags:
    - name: RFQ
paths:
    /rfqs:
        post:
            tags:
                - RFQ
            description: Create a quote
            operationId: createQuote
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Quotation"
            responses:
                "200":
                    description: OK
components:
    schemas:
        Quotation:
            type: object
            properties:
                id:
                    type: integer
                    format: uuid
                product:
                    type: string
                    maxLength: 20
                quantity:
                    type: integer
                    format: int32
                    minimum: 0
                    maximum: 1000
                price:
                    type: number
                    minimum: 0
                shipment:
                    type: string
                mode:
                    type: string
